export const documentData = [
  { docType: 'All Reports & Publications', count: 10 },
  { docType: 'Annual Therapy Update', count: 14 },
  { docType: 'Transmittals', count: 65 },
  { docType: 'HCPCS Quarterly Update', count: 28 },
  { docType: 'LCD', count: 43 },
  { docType: 'ICD 10', count: 56 },
  { docType: 'OCE Edit 37', count: 42 },
  { docType: 'Coverage Guidance', count: 22 },
  { docType: 'Final Rules', count: 38 },
  { docType: 'Draft Rules', count: 17 },
  { docType: 'Coding Updates', count: 61 },
  { docType: 'Regulatory Notices', count: 33 },
  { docType: 'Policy Updates', count: 27 },
  { docType: 'CMS Manual', count: 49 },
  { docType: 'Provider Bulletins', count: 31 },
  { docType: 'Medicare Advantage Notices', count: 19 },
  { docType: 'National Coverage Determinations', count: 44 },
  { docType: 'Local Coverage Determinations', count: 36 },
  { docType: 'Quality Measures', count: 23 },
  { docType: 'Reimbursement Updates', count: 57 },
  { docType: 'Utilization Reports', count: 41 },
  { docType: 'Enforcement Notices', count: 29 },
  { docType: 'Training Materials', count: 15 },
  { docType: 'Compliance Reports', count: 47 },
  { docType: 'Billing Instructions', count: 34 },
  { docType: 'Payment Policies', count: 52 },
  { docType: 'Audit Findings', count: 26 },
  { docType: 'Medical Necessity Guides', count: 39 },
  { docType: 'Technology Assessments', count: 21 },
  { docType: 'Research Publications', count: 62 },
];
