export const documentData = [
  { document_type: 'All Reports & Publications', count: 10 },
  { document_type: 'Annual Therapy Update', count: 14 },
  { document_type: 'Transmittals', count: 65 },
  { document_type: 'HCPCS Quarterly Update', count: 28 },
  { document_type: 'LCD', count: 43 },
  { document_type: 'ICD 10', count: 56 },
  { document_type: 'OCE Edit 37', count: 42 },
  { document_type: 'Coverage Guidance', count: 22 },
  { document_type: 'Final Rules', count: 38 },
  { document_type: 'Draft Rules', count: 17 },
  { document_type: 'Coding Updates', count: 61 },
  { document_type: 'Regulatory Notices', count: 33 },
  { document_type: 'Policy Updates', count: 27 },
  { document_type: 'CMS Manual', count: 49 },
  // { document_type: 'Provider Bulletins', count: 31 },
  // { document_type: 'Medicare Advantage Notices', count: 19 },
  // { document_type: 'National Coverage Determinations', count: 44 },
  // { document_type: 'Local Coverage Determinations', count: 36 },
  // { document_type: 'Quality Measures', count: 23 },
  // { document_type: 'Reimbursement Updates', count: 57 },
  // { document_type: 'Utilization Reports', count: 41 },
  // { document_type: 'Enforcement Notices', count: 29 },
  // { document_type: 'Training Materials', count: 15 },
  // { document_type: 'Compliance Reports', count: 47 },
  // { document_type: 'Billing Instructions', count: 34 },
  // { document_type: 'Payment Policies', count: 52 },
  // { document_type: 'Audit Findings', count: 26 },
  // { document_type: 'Medical Necessity Guides', count: 39 },
  // { document_type: 'Technology Assessments', count: 21 },
  // { document_type: 'Research Publications', count: 62 },
  // { document_type: 'Clinical Guidelines', count: 35 },
  // { document_type: 'Patient Education Materials', count: 18 },
  // { document_type: 'Safety Notices', count: 24 },
  // { document_type: 'Operational Procedures', count: 30 },
  // { document_type: 'Internal Memos', count: 20 },
  // { document_type: 'Budget Reports', count: 27 },
  // { document_type: 'Staff Training Plans', count: 33 },
  // { document_type: 'Meeting Minutes', count: 22 },
  // { document_type: 'Project Updates', count: 40 },
  // { document_type: 'Annual Reports', count: 50 },
  // { document_type: 'IT Policies', count: 32 },
  // { document_type: 'Clinical Trial Reports', count: 46 },
  // { document_type: 'Risk Assessment Reports', count: 25 },
  // { document_type: 'Environmental Health Guidelines', count: 19 },
  // { document_type: 'Strategic Plans', count: 28 },
  // { document_type: 'Medical Device Updates', count: 37 },
  // { document_type: 'Patient Safety Reports', count: 23 },
  // { document_type: 'Emergency Protocols', count: 21 },
  // { document_type: 'Internal Audit Reports', count: 29 },
  // { document_type: 'Health Policy Briefs', count: 31 },
];
